# NumPy Practice

In [1]:
# Import NumPy as its abbreviation 'np'
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as imread

In [2]:
# Create a 1-dimensional NumPy array using np.array()
np.random.seed(0)
array_1 = np.random.randint(0,10,size=(1,))

# Create a 2-dimensional NumPy array using np.array()
array_2 = np.random.randint(0,10, size=(2,2))

# Create a 3-dimensional Numpy array using np.array()
array_3 = np.random.randint(0,10, size=(2,3,3))

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array_1.shape, array_1.dtype, array_1.size, type(array_1)

((1,), dtype('int64'), 1, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
array_2.shape, array_2.dtype, array_2.size, type(array_2)

((2, 2), dtype('int64'), 4, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
array_3.shape, array_3.dtype, array_3.size, type(array_3)

((2, 3, 3), dtype('int64'), 18, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
array_2_df = pd.DataFrame(array_2)
array_2_df

0  1
0  0  3
1  3  7

In [8]:
# Create an array of shape (10, 2) with only ones
array_ones = np.ones((10,2))
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
array_zeros = np.zeros((7,2,3))
array_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
array_range = np.arange(0,100,3)
array_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [15]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.seed(0)
random_array = np.random.randint(0,10,(7,2))
random_array

array([[5, 0],
       [3, 3],
       [7, 9],
       [3, 5],
       [2, 4],
       [7, 6],
       [8, 8]])

In [16]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.seed(0)
random_floats = np.random.random((3,5))
random_floats

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [17]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_2 = np.random.randint(0,10,(4,6))
random_array_2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [18]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(0)
random_array_3 = np.random.randint(1,10, (3,7))

# Find the unique numbers in the array you just created
np.unique(random_array_3)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Find the 0'th index of the latest array you created
random_array_3[0]

array([6, 1, 4, 4, 8, 4, 6])

In [22]:
# Get the first 2 rows of latest array you created
random_array_3[:2]

array([[6, 1, 4, 4, 8, 4, 6],
       [3, 5, 8, 7, 9, 9, 2]])

In [23]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_3[:2,:2]

array([[6, 1],
       [3, 5]])

In [26]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(0)
arr1 = np.random.randint(0,10,(3,5))
arr2 = np.ones((3,5))
arr1,arr2

(array([[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [27]:
# Add the two arrays together
arr1 + arr2

array([[ 6.,  1.,  4.,  4.,  8.],
       [10.,  4.,  6.,  3.,  5.],
       [ 8.,  7.,  9.,  9.,  2.]])

In [28]:
# Create another array of ones of shape (5, 3)
arr3 = np.zeros((5,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
# Try add the array of ones and the other most recent array together
arr2.shape, arr3.shape
arr3 = arr3.T

In [37]:
# Create another array of ones of shape (3, 5)
arr4 = np.ones((3,5))
arr4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
# Subtract the new array of ones from the other most recent array
arr4 - arr3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
# Multiply the ones array with the latest array
arr4 * arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
# Take the latest array to the power of 2 using '**'
arr1 ** 2

array([[25,  0,  9,  9, 49],
       [81,  9, 25,  4, 16],
       [49, 36, 64, 64,  1]])

In [47]:
# Do the same thing with np.square()
np.sqrt(arr1)

array([[2.23606798, 0.        , 1.73205081, 1.73205081, 2.64575131],
       [3.        , 1.73205081, 2.23606798, 1.41421356, 2.        ],
       [2.64575131, 2.44948974, 2.82842712, 2.82842712, 1.        ]])

In [48]:
# Find the mean of the latest array using np.mean()
np.mean(arr1)

4.733333333333333

In [49]:
# Find the maximum of the latest array using np.max()
np.max(arr1)

9

In [50]:
# Find the minimum of the latest array using np.min()
np.min(arr1)

0

In [51]:
# Find the standard deviation of the latest array
np.std(arr1)

2.6449112566503166

In [52]:
# Find the variance of the latest array
np.var(arr1)

6.995555555555556

In [56]:
# Reshape the latest array to (3, 5, 1)
arr1 = arr1.reshape((3,5,1))
arr1

array([[[5],
        [0],
        [3],
        [3],
        [7]],

       [[9],
        [3],
        [5],
        [2],
        [4]],

       [[7],
        [6],
        [8],
        [8],
        [1]]])

In [57]:
# Transpose the latest array
arr1.T

array([[[5, 9, 7],
        [0, 3, 6],
        [3, 5, 8],
        [3, 2, 8],
        [7, 4, 1]]])

In [58]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr5 = np.random.randint(0,10,(3,3))
arr6 = np.random.randint(0,10,(3,2))
arr5, arr6

(array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9]]),
 array([[4, 3],
        [0, 3],
        [5, 0]]))

In [59]:
# Perform a dot product on the two newest arrays you created
np.dot(arr5, arr6)

array([[59, 39],
       [57, 27],
       [81, 51]])

In [61]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr7 = np.random.randint(0,10,(4,3))
arr8 = np.random.randint(0,10,(4,3))
arr7, arr8

(array([[0, 4, 7],
        [3, 2, 7],
        [2, 0, 0],
        [4, 5, 5]]),
 array([[6, 8, 4],
        [1, 4, 9],
        [8, 1, 1],
        [7, 9, 9]]))

In [63]:
# Perform a dot product on the two newest arrays you created
np.dot(arr7, arr8.T)

array([[ 60,  79,  11,  99],
       [ 62,  74,  33, 102],
       [ 12,   2,  16,  14],
       [ 84,  69,  42, 118]])

In [64]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
np.random.seed(0)
arr9 = np.random.randint(0,10, (3,5))
arr10 = np.random.randint(0,10, (3,5))
arr9, arr10

(array([[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1]]),
 array([[6, 7, 7, 8, 1],
        [5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0]]))

In [65]:
# Compare the two arrays with '>'
arr9 > arr10

array([[False, False, False, False,  True],
       [ True, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [66]:
# Compare the two arrays with '>='
arr9 >= arr10

array([[False, False, False, False,  True],
       [ True, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [67]:
# Find which elements of the first array are greater than 7
arr9 > 7

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False,  True,  True, False]])

In [68]:
# Which parts of each array are equal? (try using '==')
arr9 == arr10

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [69]:
# Sort one of the arrays you just created in ascending order
np.sort(arr9)

array([[0, 3, 3, 5, 7],
       [2, 3, 4, 5, 9],
       [1, 6, 7, 8, 8]])

In [70]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr9)

array([[1, 2, 3, 0, 4],
       [3, 1, 4, 2, 0],
       [4, 1, 0, 2, 3]])

In [72]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr9)

5

In [73]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr9)

1

In [74]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr9, axis=1)

array([4, 0, 2])

In [75]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr9, axis=0)

array([0, 0, 0, 1, 2])

In [79]:
# Create an array of normally distributed random numbers
np.random.seed()
arr11 = np.random.randn(3,5)
arr11

array([[ 0.79250588,  0.154125  ,  0.04302911, -1.40457333, -1.65569307],
       [-1.59882884, -0.91618714, -0.15702608, -1.69455251, -0.2366589 ],
       [ 0.24303879, -0.88362853, -0.33579218, -0.17099555,  0.44449634]])

In [83]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])